// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hstflhelvdajwlcdtveq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzdGZsaGVsdmRhandsY2R0dmVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwOTAzMTUsImV4cCI6MjA3MTY2NjMxNX0.tyIbsmF3I0pCj5mJBxwcTGaPBW4CEKYFdZGr-N__Tgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});